In [1]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from numpy.random import rand
from numpy.linalg import solve, inv

### 這邊先生成一個3x3的矩陣

In [2]:
a = np.arange(2,11).reshape(3,3)

### 然後矩陣a本來長這樣：

In [3]:
a

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

### 試著將一三橫列（row）互換之後

In [4]:
n = 0
m = 2
b = a[n]
a[n] = a[m]
a[m] = b

### 這傢伙的1、3row就會很衰敗的變同一個東西

In [6]:
a

array([[ 8,  9, 10],
       [ 5,  6,  7],
       [ 8,  9, 10]])

### 於是這邊來試看看生成單位矩陣，並讓他隨機產生基本矩陣

In [7]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from numpy.random import rand
from numpy.linalg import solve, inv
import random as rd

In [9]:
a = rd.randint(0,99)
b = rd.randint(a,199)
c = np.random.randint(a,b,(3,3))
d = np.eye(3)
c1 = inv(c)
c

array([[32, 38, 33],
       [38, 57, 25],
       [44, 41, 49]])

In [10]:
d = np.eye(3)
dr = rd.randint(0,2)
d[dr] = d[dr]*rd.randint(0,99)

In [11]:
d

array([[ 1.,  0.,  0.],
       [ 0., 15.,  0.],
       [ 0.,  0.,  1.]])

### P.S. 這邊舉第二種基本列運算為例子